#!/bin/sh
#
#This is a script which will be called
#when emacs save a file and can do some
#action on the saved file
#
_fnodir=`basename $1`
_odir=`dirname $1`
# Following line will get the real
# directory of file
_dirname=`cd $_odir;/bin/sh -c pwd`
_filename=$_dirname/$_fnodir
_action_name=.on_file_saved
_dirname=$_filename

while :; do
    _dirname=`dirname $_dirname`
    _action=$_dirname/$_action_name
    if [ -x $_action ]; then
	_saved_dir=`pwd`
	cd $_dirname
	$_action $_filename
	cd $_saved_dir
    fi
    if [ "X$_dirname" = "X/" ]; then
	break
    fi
done

